### ISSUE TITLE
Can someone update the doc with instructions for where to put the .neovintageous configuration file on Mac ? 

### ISSUE THREAD

**Issue by zaka634** [gerardroche/gerardroche.github.io#9]

**Comment by gerardroche** [comment]
Use the Command Pallette command: `NeoVIntageous: Open RC File`

**Comment by gerardroche** [comment]
Don't forget to run the Command Palette command `NeoVintageous: Reload RC File` or restart sublime for any new mappings to take effect.

You can see more help via `:help nv`.

**Comment by gerardroche** [comment]
NeoVintageous creates the rc file in the User packages directory. You can find the user packages via the `Preferences > Browse Packages` menu. The rc file is created inside the `User` directory at `User/.neovintageousrc`
